import Head from "next/head";
import Filter from "../components/filter";
import { Box } from "@mui/material";

export default function Home() {
  return (
    <div>
      <Head>
        <title>safrat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box
          sx={{
            width: "100vw",
            height: "100vh",
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <Filter />
        </Box>
      </main>
    </div>
  );
}
